# Site
repository: cris-agbal/cris-agbal.github.io
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Cristian Emmanuel Aguilar Balvaneda
title: Fullstack developer
email: cristian.agbal@gmail.com
# email_title: Email (Email title override)
phone: 3311652251
# phone_title: Phone (Phone title override)
#website: Your website (eg. https://google.com)(optional)
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: jekyllrb
github_username:  cris-agbal
#stackoverflow_username: "00000001"
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
instagram_username: cristian_aguilarf
#linkedin_username: jekyll
#xing_username: jekyll
#pinterest_username: jekyll
#youtube_username: jekyll
#orcid_username: 0000-0000-0000-0000
#googlescholar_username: D847cGsAAAAJ

# Additional icon links
additional_links:
- title: Link name
  icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
  url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: Acerca de mi
about_profile_image: images/face.jpg
about_content: | # this will include new lines to allow paragraphs
  Hola, mi nombre es Cristian, soy estudiante de ingeniería informática de sabe cual semestre, tengo poca experiencia con proyectos de programacion grandes pero me gusta mucho aprender. Me llama mucho la atención el <mark>desarrollo web</mark> y las <mark>redes</mark>.

  Algunas de las cosas que me interesan son:
    - Angular
    - React
    - JavaScript
    - Desarrollo movil
    - Holaaaaaaaaaaa

content:
  - title: Proyectos # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Proyecto de la NASA
        link: https://cris-agbal.github.io/cris-agbal.github.io
        link_text: https://www.nasa.gov/
        additional_links:
          - title:  Pagina del proyecto
            icon: fab fa-github
            url: https://cris-agbal.github.io/cris-agbal.github.io
        quote: >
          Proyecto de aplicaciones para controlar nave hacia andromeda.
        description: | # this will include new lines to allow paragraphs
          Desarrollé aplicaciones y algoritmos para el sistema ADM-5000 que viajó hacía la galaxia de Andrómeda.
          Desarrollo de la interfaz y conexiones de control con el sistema
  - title: Experiencia
    layout: list
    content:
      - layout: right
        title: IBM
        sub_title: Test Analzer
        caption: Abril 2022 - presente
        link: https://ibm.com
        quote: >
          Empresa del giro electrónico dedicada a la elaboración de servidores
        description: | # this will include new lines to allow paragraphs
          Debuggeo y realización de pruebas a equipos de la familia OpenPower tanto a equipos de la familia Z 

       - layout: right
        title: Productos de Trigo
        sub_title: Auxiliar de sistemas
        caption: Abril 2021 - Abril 2022
        link:
        quote: >
          Empresa del giro alimenticio.
        description: | # this will include new lines to allow paragraphs
          -Mantenimiento preventivo a equipo de computo
          -Respaldo de bases de datos
          -Control de usuarios en applicaciones de la empresa
          -Control de equipo de computo

  - title: Educación
    layout: list
    content:
      - layout: top-right
        title: Centro Universitario de Ciencias Exactas e Ingenierías
        sub_title: "100" on everything.
        caption: 2017 - presente
        quote: >
          Inegnieria en informatica oriantada al desarrollo.
        description: | # this will include new lines to allow paragraphs
          -Desarrollo de apps.
          -Desarrollo web
          -Redes.
          -Bases de datos.
          -Servidores
       - layout: top-right
         title: Preparatoria UdeG
         sub_title: "100" on everything.
         caption: 2014 - 2017
         quote: >
          Bachillerato General
         description: | # this will include new lines to allow paragraphs
          -Desarrollo web
          -Matematicas
          -Algoritmos

  - title: Un poco mas de mi
    layout: text
    content: | # this will include new lines to allow paragraphs
      Me gusta mucho leer cualquier cosa, puede ser un **libro** o un **manga**.
      Por lo general salgo a la calle a **patinar** o andar en **bici**, esucho **música** y me gusta tomar fotos con mi celular.

      Las habilidades que tengo son:
      -Aprendizaje rapido
      -Trabajo en equipo
      -Trabajo bajo presión

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
